# Generated by Django 6.1.1 on 2026-09-16 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP at login; empty when unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text='User-Agent header at login (first 255 chars).', max_length=255),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Account used at login; emptied if the account is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
