# Generated by Django 6.1.1 on 2026-09-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_googleaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAccount',
        ),
    ]
