# Generated by Django 6.1.1 on 2026-09-12 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('Ploughing', 'Ploughing'), ('Rotavator', 'Rotavator work'), ('Cultivation', 'Cultivation'), ('Harvesting', 'Harvesting'), ('Irrigation', 'Irrigation')], max_length=20)),
                ('work_date', models.DateField()),
                ('area', models.DecimalField(decimal_places=2, help_text='Area of work in acres.', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged in Rs.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(help_text='Farmer for whom this work was done.', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='farmers.farmer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', '-id'],
            },
        ),
    ]
