# Generated by Django 6.1.1 on 2026-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour in Rs for irrigation.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='irrigation_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='irrigation_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('Ploughing', 'Ploughing'), ('Rotavator', 'Rotavator work'), ('Cultivation', 'Cultivation'), ('Harvesting', 'Harvesting'), ('Irrigation', 'Irrigation'), ('Other', 'Other')], max_length=20),
        ),
    ]
