# Generated by Django 6.1.1 on 2026-09-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_hourly_rate_work_irrigation_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area of work in acres.', max_digits=10, null=True),
        ),
    ]
