# Generated by Django 6.1.1 on 2026-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_work_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='rate_per_acre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per acre in Rs for land leveling.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('Ploughing', 'Ploughing'), ('Rotavator', 'Rotavator work'), ('Cultivation', 'Cultivation'), ('Harvesting', 'Harvesting'), ('Irrigation', 'Irrigation'), ('Other', 'Other'), ('Land Leveling', 'Land Leveling')], max_length=20),
        ),
    ]
