# Generated by Django 6.1.1 on 2026-09-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_rate_per_acre_alter_work_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='field_location',
            field=models.CharField(help_text='Where the work was performed.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='remark',
            field=models.TextField(blank=True, help_text='Additional information about the work.', null=True),
        ),
    ]
