# Generated by Django 6.1.1 on 2026-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_field_location_work_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_description',
            field=models.TextField(blank=True, help_text='Description of the work for Other work type.', null=True),
        ),
    ]
