# Generated by Django 6.1.1 on 2026-09-16 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
        ('works', '0006_work_work_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('user', 'farmer', 'work_type', 'work_date'), name='unique_work_per_farmer_type_date'),
        ),
    ]
