# Generated by Django 6.1.1 on 2026-09-14 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('problem_type', models.CharField(choices=[('Login Problem', 'Login Problem'), ('Work Record Problem', 'Work Record Problem'), ('Billing Problem', 'Billing Problem'), ('Payment Problem', 'Payment Problem'), ('Report Problem', 'Report Problem'), ('Dashboard Problem', 'Dashboard Problem'), ('Language Problem', 'Language Problem'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='problem_screenshots/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
